name: chattts_demo
description: A demo app for ChatTTS TensorFlow model
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/chattts_model.tflite 