name: Check Pull Request Format

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  # This workflow closes invalid PR
  change-or-close-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Change Base Branch
        if: github.event.pull_request.base.ref != 'dev'
        uses: actions/github-script@v4
        id: change-base
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const newBase = 'dev';
            try {
              const result = await github.pulls.update({
                owner,
                repo,
                pull_number: number,
                base: newBase
              });
              console.log(result);
              return 'success';
            } catch (error) {
              console.log(error);
              return 'failed';
            }

      - name: Close PR if it is not pointed to dev Branch
        if: "github.event.pull_request.base.ref != 'dev' && steps.change-base.outputs.result == 'failed'"
        uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "Invalid PR to `non-dev` branch `${{ github.event.pull_request.base.ref }}`."

  pull-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    continue-on-error: true

    steps:
      - name: Checkout
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Black
        run: pip install "black[jupyter]"

      - name: Run Black
        # run: black $(git ls-files '*.py')
        run: black .

      - name: Commit back
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "chore(format): run black on ${{github.ref_name}}"
          git push
